language: csharp
solution: Stories.sln
mono: none
dist: trusty
sudo: required
dotnet: 1.0.4

before_install:
- chmod +x ./build/scripts/build.sh
- chmod +x ./build/scripts/test.sh
- "npm config set spin false"
- "npm install -g npm@^3"
- "npm install -g gulp@^3"

script:
- ./build/scripts/build.sh --quiet verify
- ./build/scripts/test.sh --quiet verify
