language: csharp
solution: Stories.sln
mono: none
dist: trusty
sudo: required
dotnet: 1.0.4

before_install:
- npm install gulp --save-dev
- npm install
- chmod +x ./build/scripts/build.sh
- chmod +x ./build/scripts/test.sh

script:
- ./build/scripts/build.sh --quiet verify
- ./build/scripts/test.sh --quiet verify
